name: e_commerce_project
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

#--------------------------packages--------------------#
dependencies:
  flutter:
    sdk: flutter
# utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

#  icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

#  state management
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_database: ^11.0.4
  firebase_storage: ^12.1.2
  firebase_auth: ^5.1.3
  lottie: ^3.1.2
  connectivity_plus: ^5.0.1
  google_sign_in: ^6.1.6
  shimmer: ^3.0.0
  image_picker: ^1.1.2


#--------------------- package end ----------------$
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


#------------------ local assets -----------------#
  assets:
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/payment_methods/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/user/
    - assets/images/reviews/
    - assets/images/products/
    - assets/logos/
  

  
#----------------- local fonts -------------------------#

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
